language: cpp
dist: focal
os: linux

jobs:
  include:
    - compiler: gcc

script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug ..
  - make

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

addons:
  apt:
    packages:
      - gcc-10
      - cmake

notifications:
  email: false
